<?php
define('XS_SNAPSHOT_MAX_POLICIES_PER_USER', 1);
/**
 * Defines drop-down select element for snapshot policies.
 *
 * @return array
 *   Array for the form select element.
 */
function _xs_get_snapshots_policy_type() {
  $query = db_select('xs_snapshot_policy_type', 't');
  $query->fields('t', array('id', 'label'));
  $result = $query->execute();

  $options = array();
  while ($row = $result->fetchAssoc()) {
    $options[$row['id']] = $row['label'];
  }

  return $options;
}

/**
 * Implements hook_theme().
 */
function xs_snapshot_policy_theme($existing, $type, $theme, $path) {
  return array(
    'xs_snapshot_policy_output' => array(
      'template' => 'templates/xs-snapshot-policy-output',
      'file' => 'theme/xs_snapshot_policy.theme.inc',
      'preprocess functions' => array('xs_snapshot_policy_output_preprocess'),
      'variables' => array(
        'node' => NULL,
      ),
    ),
  );
}

/**
 * Form definition for 'xs_snapshot_policy_create_form'.
 */
function xs_snapshot_policy_create_form($form, &$form_state, $nid) {
  $form_state['storage']['node_nid'] = $nid;

  $form['#prefix'] = '<div id="new_snapshot_policy_form" class="modal fade" role="dialog" aria-labelledby="gridSystemModalLabel"><div class="modal-dialog" role="document"><div class="modal-content">';
  $form['#suffix'] = '</div></div></div>';

  $form['header'] = array(
    '#markup' => '<div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="gridSystemModalLabel">Create new automated snapshots policy</h4>
                </div>',
  );

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Policy name'),
    '#size' => 64,
    '#maxlength' => 64,
    '#description' => t('Give a name, to this policy'),
    '#required' => TRUE,
    '#prefix' => '<div class="modal-body"><div class="row"><div class="col-md-12">',
    '#suffix' => '</div></div></div>',
  );

  $form['type_id'] = array(
    '#type' => 'select',
    '#title' => t('Select snapshots type'),
    '#options' => _xs_get_snapshots_policy_type(),
    '#description' => t('Select how often you want snapshots to be created'),
    '#required' => TRUE,
  );

  $form['actions'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array('modal-footer'),
    ),
  );

  $form['actions']['cancel'] = array(
    '#type' => 'button',
    '#attributes' => array(
      'type' => 'button',
      'class' => array('btn btn-default'),
      'data-dismiss' => 'modal',
    ),
    '#value' => t('Cancel'),
  );

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => XS_API_SNAPSHOT_CREATE_BUTTON_TITLE,
    '#attributes' => array(
      'type' => 'button',
      'class' => array('btn btn-primary'),
    ),
  );

  return $form;
}

function xs_snapshot_policy_create_form_validate($form, &$form_state) {
  $linked_node = node_load($form_state['storage']['node_nid']);
  $form_state['storage']['linked_node'] = $linked_node;
  if (!xs_actions_access_callback($linked_node)) {
    drupal_set_message('Validation error. Unable to create snapshots automation policy.', 'error');
    return form_set_error(NULL, 'Validation error. Unable to create snapshots automation policy.');
  }
}

function xs_snapshot_policy_create_form_submit($form, &$form_state) {
  module_load_include('inc', 'xs_snapshot_policy', 'xs_snapshot_policy.admin');
  try {
    $node_wrapper = entity_metadata_wrapper('node', $form_state['storage']['linked_node']);
  }
  catch (Exception $e) {
    watchdog('XS_SNAP_POLICY', $e->getMessage(), WATCHDOG_ERROR);
  }

//  xs_snapshot_policy_add($form_state['values']['type_id']);

  $policy = entity_create('xs_snapshot_policy', $form_state['values']);
  $policy->title = $form_state['values']['title'];
  $policy->type_id = $form_state['values']['type_id'];
  $policy->uid = $node_wrapper->field_xs_vps_owner->value();
  $policy->created = time();
  $policy->changed = time();
  entity_save('xs_snapshot_policy', $policy);
}

/**
 * Implements hook_entity_info().
 */
function xs_snapshot_policy_entity_info() {
  $return = array(
    'xs_snapshot_policy' => array(
      'label' => t('Snapshot Policy'),
      'entity class' => 'SnapshotPolicy',
      'controller class' => 'SnapshotPolicyController',
      'base table' => 'xs_snapshot_policy',
      'fieldable' => TRUE,
      'entity keys' => array(
        'id' => 'spid',
        'bundle' => 'type_id',
      ),
      'bundle keys' => array(
        'bundle' => 'type_id',
      ),
      'bundles' => array(),
      'load hook' => 'xs_snapshot_policy_load',
      'view modes' => array(
        'full' => array(
          'label' => t('Default'),
          'custom settings' => FALSE,
        ),
      ),
      'label callback' => 'entity_class_label',
      'uri callback' => 'entity_class_uri',
      'module' => 'xs_snapshot_policy',
      'access callback' => 'xs_snapshot_policy_access',
    ),
  );
  $return['xs_snapshot_policy_type'] = array(
    'label' => t('Snapshot Policy Type'),
    'entity class' => 'SnapshotPolicyType',
    'controller class' => 'SnapshotPolicyTypeController',
    'base table' => 'xs_snapshot_policy_type',
    'fieldable' => FALSE,
    'bundle of' => 'xs_snapshot_policy',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'module' => 'xs_snapshot_policy',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/structure/xs/snapshot-policy-types',
      'file' => 'xs_snapshot_policy.admin.inc',
      'controller class' => 'ExampleTaskTypeUIController',
    ),
    'access callback' => 'xs_snapshot_policy_type_access',
  );

  return $return;
}

/**
 * Implements hook_entity_info_alter().
 */
function xs_snapshot_policy_entity_info_alter(&$entity_info) {
  foreach (xs_snapshot_policy_types() as $type => $info) {
    $entity_info['xs_snapshot_policy']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/xs/snapshot-policy-types/manage/%xs_snapshot_policy_type',
        'real path' => 'admin/structure/xs/snapshot-policy-types/manage/' . $type,
        'bundle argument' => 4,
      ),
    );
  }
}

/**
 * Implements hook_menu().
 */
function xs_snapshot_policy_menu() {
  $items = array();

  // @todo: Consider removing this.
  $items['snapshot-policy/add'] = array(
    'title' => 'Add snapshot-policy',
    'page callback' => 'xs_snapshot_policy_admin_add_page',
    'access arguments' => array('administer xs_snapshot_policy entities'),
    'file' => 'xs_snapshot_policy.admin.inc',
    'type' => MENU_LOCAL_ACTION,
    'tab_parent' => 'snapshot-policy',
    'tab_root' => 'snapshot-policy',
  );

  // @todo: Consider removing this.
  $snapshot_policy_uri = 'snapshot-policy/%xs_snapshot_policy';
  $snapshot_policy_uri_argument_position = 1;

  // @todo: Consider removing this.
  $items[$snapshot_policy_uri] = array(
    'title callback' => 'entity_label',
    'title arguments' => array(
      'xs_snapshot_policy',
      $snapshot_policy_uri_argument_position
    ),
    'page callback' => 'xs_snapshot_policy_view',
    'page arguments' => array($snapshot_policy_uri_argument_position),
    'access callback' => 'entity_access',
    'access arguments' => array(
      'view',
      'xs_snapshot_policy',
      $snapshot_policy_uri_argument_position
    ),
    'file' => 'xs_snapshot_policy.pages.inc',
  );

  // @todo: Consider removing this.
  $items[$snapshot_policy_uri . '/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  // @todo: Consider removing this.
  $items[$snapshot_policy_uri . '/delete'] = array(
    'title' => 'Delete snapshot-policy',
    'title callback' => 'xs_snapshot_policy_label',
    'title arguments' => array($snapshot_policy_uri_argument_position),
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'xs_snapshot_policy_delete_form',
      $snapshot_policy_uri_argument_position
    ),
    'access callback' => 'entity_access',
    'access arguments' => array(
      'edit',
      'xs_snapshot_policy',
      $snapshot_policy_uri_argument_position
    ),
    'file' => 'xs_snapshot_policy.admin.inc',
  );

  // @todo: Consider removing this.
  $items[$snapshot_policy_uri . '/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array(
      'xs_snapshot_policy_form',
      $snapshot_policy_uri_argument_position
    ),
    'access callback' => 'entity_access',
    'access arguments' => array(
      'edit',
      'xs_snapshot_policy',
      $snapshot_policy_uri_argument_position
    ),
    'file' => 'xs_snapshot_policy.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );

  // @todo: Consider removing this.
  foreach (xs_snapshot_policy_types() as $type => $info) {
    $items['snapshot-policy/add/' . $type] = array(
      'title' => 'Add snapshot-policy',
      'page callback' => 'xs_snapshot_policy_add',
      'page arguments' => array(2),
      'access callback' => 'entity_access',
      'access arguments' => array('create', 'xs_snapshot_policy', $type),
      'file' => 'xs_snapshot_policy.admin.inc',
    );
  }

  $items['admin/structure/xs/snapshot-policy-types/%xs_snapshot_policy_type/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('xs_snapshot_policy_type_form_delete_confirm', 4),
    'access arguments' => array('administer xs_snapshot_policy types'),
    'weight' => 1,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'xs_snapshot_policy.admin.inc',
  );

  $items['node/%node/xs-snapshot-policy'] = array(
    'title' => 'Automated Snaphot Policy',
    'description' => 'Manage server automated snapshot policy',
    'page callback' => 'xs_snapshot_policy_display_callback',
    'page arguments' => array(1),
    'access callback' => 'entity_access',
    'access arguments' => array('create', 'xs_snapshot_policy'),
    'weight' => 65,
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function xs_snapshot_policy_display_callback($node) {
  return theme('xs_snapshot_policy_output', array('node' => $node));
}

/**
 * Implements hook_permission().
 */
function xs_snapshot_policy_permission() {
  $permissions = array(
    'administer xs_snapshot_policy types' => array(
      'title' => t('Administer snapshot-policy types'),
      'description' => t('Allows users to configure snapshot-policy types and their fields.'),
      'restrict access' => TRUE,
    ),
    'create xs_snapshot_policy entities' => array(
      'title' => t('Create XenServer Snapshot Policies'),
      'description' => t('Allows users to create XenServer Snapshot Policies.'),
      'restrict access' => TRUE,
    ),
    'view xs_snapshot_policy entities' => array(
      'title' => t('View XenServer Snapshot Policies'),
      'description' => t('Allows users to view XenServer Snapshot Policies.'),
      'restrict access' => TRUE,
    ),
    'edit any xs_snapshot_policy entities' => array(
      'title' => t('Edit any XenServer Snapshot Policies'),
      'description' => t('Allows users to edit any XenServer Snapshot Policies.'),
      'restrict access' => TRUE,
    ),
    'edit own xs_snapshot_policy entities' => array(
      'title' => t('Edit own XenServer Snapshot Policies'),
      'description' => t('Allows users to edit own XenServer Snapshot Policies.'),
      'restrict access' => TRUE,
    ),
  );

  return $permissions;
}

/**
 * Implements hook_entity_property_info_alter().
 */
function xs_snapshot_policy_entity_property_info_alter(&$info) {
  $properties = &$info['xs_snapshot_policy']['properties'];
  $properties['created'] = array(
    'label' => t("Date created"),
    'type' => 'date',
    'description' => t("The date the node was posted."),
    'setter callback' => 'entity_property_verbatim_set',
    'setter permission' => 'administer nodes',
    'schema field' => 'created',
  );
  $properties['changed'] = array(
    'label' => t("Date changed"),
    'type' => 'date',
    'schema field' => 'changed',
    'description' => t("The date the node was most recently updated."),
  );
  $properties['uid'] = array(
    'label' => t("Author"),
    'type' => 'user',
    'description' => t("The author of the snapshot-policy."),
    'setter callback' => 'entity_property_verbatim_set',
    'setter permission' => 'administer xs_snapshot_policy entities',
    'required' => TRUE,
    'schema field' => 'uid',
  );
}

/**
 * Access callback for snapshot-policy.
 */
function xs_snapshot_policy_access($op, $snapshot_policy, $account = NULL, $entity_type = NULL) {
  global $user;

  if (!isset($account)) {
    $account = $user;
  }
  switch ($op) {
    case 'create':
      return user_access('administer xs_snapshot_policy entities', $account)
      || user_access('create xs_snapshot_policy entities', $account);
    case 'view':
      return user_access('administer xs_snapshot_policy entities', $account)
      || user_access('view xs_snapshot_policy entities', $account);
    case 'edit':
      return user_access('administer xs_snapshot_policy entities')
      || user_access('edit any xs_snapshot_policy entities')
      || (user_access('edit own xs_snapshot_policy entities') && ($snapshot_policy->uid == $account->uid));
  }
}

/**
 * Load a snapshot-policy.
 */
function xs_snapshot_policy_load($tkid, $reset = FALSE) {
  $tasks = xs_snapshot_policy_load_multiple(array($tkid), array(), $reset);
  return reset($tasks);
}

/**
 * Load multiple XenServer Snapshot Policies based on certain conditions.
 */
function xs_snapshot_policy_load_multiple($tkids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('xs_snapshot_policy', $tkids, $conditions, $reset);
}

/**
 * Save snapshot-policy.
 */
function xs_snapshot_policy_save($snapshot_policy) {
  entity_save('xs_snapshot_policy', $snapshot_policy);
}

/**
 * Delete single snapshot-policy.
 */
function xs_snapshot_policy_delete($task) {
  entity_delete('xs_snapshot_policy', entity_id('xs_snapshot_policy', $task));
}

/**
 * Delete multiple XenServer Snapshot Policies.
 */
function xs_snapshot_policy_delete_multiple($task_ids) {
  entity_delete_multiple('xs_snapshot_policy', $task_ids);
}

/**
 * Access callback for snapshot-policy Type.
 */
function xs_snapshot_policy_type_access($op, $entity = NULL) {
  return user_access('administer xs_snapshot_policy types');
}

/**
 * Load snapshot-policy Type.
 */
function xs_snapshot_policy_type_load($snapshot_policy_type) {
  return xs_snapshot_policy_types($snapshot_policy_type);
}

/**
 * List of snapshot-policy Types.
 *
 * @todo: In use.
 */
function xs_snapshot_policy_types($type_id = NULL) {
  $type_ids = !empty($type_id) ? array($type_id) : FALSE;
  $types = entity_load('xs_snapshot_policy_type', $type_ids);

  return isset($type_id) ? reset($types) : $types;
}

/**
 * Save snapshot-policy type entity.
 */
function xs_snapshot_policy_type_save($snapshot_policy_type) {
  entity_save('xs_snapshot_policy_type', $snapshot_policy_type);
}

/**
 * Delete single case type.
 */
function xs_snapshot_policy_type_delete($snapshot_policy_type) {
  entity_delete('xs_snapshot_policy_type', entity_id('xs_snapshot_policy_type', $snapshot_policy_type));
}

/**
 * Delete multiple case types.
 */
function xs_snapshot_policy_type_delete_multiple($task_type_ids) {
  entity_delete_multiple('xs_snapshot_policy_type', $task_type_ids);
}

/**
 * Implements hook_views_api().
 */
function xs_snapshot_policy_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'xs_snapshot_policy'),
  );
}

